name: Pokedex Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Setup Application
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.6.2'
          check-latest: true

      - name: Install NPM Dependencies
        run: yarn install --ignore-engines

      - name: Build App
        run: yarn build

      - name: Run jest tests
        run: yarn test:ci

      - name: Run cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: 'http://localhost:3000'
